version: 0.2

phases:
  install:
    commands:
      # Update libs
      - apt-get update
      # Headless Chrome
      - apt-get install -y fonts-liberation libasound2 libnspr4 libnss3 libx11-xcb1 xdg-utils libxss1 libappindicator1 libindicator7
      - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      - dpkg -i google-chrome*.deb
    finally:
      - echo Installed pre-reqs
  pre_build:
    commands:
      - npm install
    finally:
      - echo npm install finished
  build:
    commands:
      - npm run build-prod
      # - npm run test:ci
    finally:
      - echo Finished building the Angular app
  post_build:
    commands:
      - aws s3 sync ./dist s3://agt-frontend-prod --acl 'public-read' --delete
    finally:
      - echo Synced the newest distribution to S3
artifacts:
  files:
    - '**/*.html'
    - '**/*.js'
    - '**/*.css'
    - '**/*.ico'
  discard-paths: yes
  base-directory: 'dist'
